import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { DistrictData, getDistrictData } from '../../utils/districtLocalStorage';
import { KindData, getKindData } from '../../utils/kindLocalStorage';
import { ClassificationData, getClassificationData } from '../../utils/classificationLocalStorage';
import { SubclassData, getSubclassesByClassId } from '../../utils/subclassLocalStorage';
import { ActualUsedData, getActualUsedByClassId } from '../../utils/actualUsedLocalStorage';
import FormView from './FormView';
import BuildingModal from './BuildingModal';
import MachineModal, { MachineData } from './MachineModal';
import PhotoModal from './PhotoModal';
import AgriculturalLandAdjustmentModal, { AgriculturalLandAdjustmentData } from './AgriculturalLandAdjustmentModal';

// Import the correct FormData interface
import { FormData } from '../../utils/tablestorages/FormDataLocalStorage';

interface FormProps {
  isOpen: boolean;
  onDismiss: () => void;
  onSuccess: () => void;
}

const Form: React.FC<FormProps> = ({ isOpen, onDismiss, onSuccess }) => {
  const [district, setDistrict] = useState<number | null>(null);
  const [declarant, setDeclarant] = useState<string>('');
  const [kind, setKind] = useState('');
  const [classification, setClassification] = useState('');
  const [subclass, setSubclass] = useState('');
  const [actualUse, setActualUse] = useState('');
  const [area, setArea] = useState<number>(0);
  const [districts, setDistricts] = useState<DistrictData[]>([]);
  const [kinds, setKinds] = useState<KindData[]>([]);
  const [classifications, setClassifications] = useState<ClassificationData[]>([]);
  const [subclasses, setSubclasses] = useState<SubclassData[]>([]);
  const [actualUses, setActualUses] = useState<ActualUsedData[]>([]);
  const [isFormValid, setIsFormValid] = useState(false);
  const [isLoadingDistricts, setIsLoadingDistricts] = useState(true);
  const [isLoadingKinds, setIsLoadingKinds] = useState(true);
  const [isLoadingClassifications, setIsLoadingClassifications] = useState(true);
  const [isLoadingSubclasses, setIsLoadingSubclasses] = useState(false);
  const [isLoadingActualUses, setIsLoadingActualUses] = useState(false);
  const [showBuildingModal, setShowBuildingModal] = useState(false);
  const [showMachineModal, setShowMachineModal] = useState(false);
  const [showPhotoModal, setShowPhotoModal] = useState(false);
  const [showAgriculturalModal, setShowAgriculturalModal] = useState(false);
  const [buildingData, setBuildingData] = useState<any>(null);
  const [machineData, setMachineData] = useState<MachineData | null>(null);
  const [agriculturalData, setAgriculturalData] = useState<AgriculturalLandAdjustmentData | null>(null);

  const isBuilding = useMemo((): boolean => {
    if (!kind || isLoadingKinds || kinds.length === 0) return false;
    const selectedKind = kinds.find(k => k.kind_id.toString() === kind);
    return selectedKind?.description?.toLowerCase().includes('building') || false;
  }, [kind, isLoadingKinds, kinds]);

  const isLandKind = useMemo((): boolean => {
    if (!kind || isLoadingKinds || kinds.length === 0) return false;
    const selectedKind = kinds.find(k => k.kind_id.toString() === kind);
    return selectedKind?.description?.toLowerCase().includes('land') || false;
  }, [kind, isLoadingKinds, kinds]);

  const isMachineryKind = useMemo((): boolean => {
    if (!kind || isLoadingKinds || kinds.length === 0) return false;
    const selectedKind = kinds.find(k => k.kind_id.toString() === kind);
    return selectedKind?.description?.toLowerCase().includes('machinery') || false;
  }, [kind, isLoadingKinds, kinds]);

  const isAgriculturalLand = useMemo((): boolean => {
    if (!kind || !classification || isLoadingKinds || isLoadingClassifications) return false;

    const selectedKind = kinds.find(k => k.kind_id.toString() === kind);
    const selectedClassification = classifications.find(c => c.class_id === classification);

    return (selectedKind?.description?.toLowerCase().includes('land') || false) &&
      (selectedClassification?.classification?.toLowerCase().includes('agricultural') || false);
  }, [kind, classification, isLoadingKinds, isLoadingClassifications, kinds, classifications]);

  const formattedActualUses = useMemo((): Array<{ value: string, label: string }> => {
    return actualUses.map(actualUse => ({
      value: actualUse.actual_used_id,
      label: `${actualUse.actual_used_id} - ${actualUse.description}`
    }));
  }, [actualUses]);

  // Create a complete FormData object with default values for all required fields
  const formData: FormData = useMemo(() => ({
    district,
    declarant,
    kind,
    classification,
    subclass,
    actualUse,
    area,
    id: '', // Will be generated by FormDataLocalStorage
    status: 'unploaded',
    uploaded: false
  }), [district, declarant, kind, classification, subclass, actualUse, area]);

  useEffect(() => {
    const loadData = async () => {
      try {
        setIsLoadingDistricts(true);
        setIsLoadingKinds(true);
        setIsLoadingClassifications(true);

        const [districtData, kindData, classificationData] = await Promise.all([
          getDistrictData(),
          getKindData(),
          getClassificationData()
        ]);

        if (districtData) setDistricts(districtData);
        if (kindData) setKinds(kindData);
        if (classificationData) setClassifications(classificationData);
      } catch (error) {
        console.error('Error loading data:', error);
      } finally {
        setIsLoadingDistricts(false);
        setIsLoadingKinds(false);
        setIsLoadingClassifications(false);
      }
    };

    if (isOpen) loadData();
  }, [isOpen]);

  useEffect(() => {
    const fetchSubclasses = async () => {
      if (!classification) {
        setSubclasses([]);
        setSubclass('');
        setIsLoadingSubclasses(false);
        return;
      }

      setIsLoadingSubclasses(true);
      try {
        const subclassData = await getSubclassesByClassId(classification);
        setSubclasses(subclassData || []);

        if (subclass && !subclassData?.some(s => s.subclass_id === subclass)) {
          setSubclass('');
        }
      } catch (error) {
        console.error('Error fetching subclasses:', error);
        setSubclasses([]);
        setSubclass('');
      } finally {
        setIsLoadingSubclasses(false);
      }
    };

    fetchSubclasses();
  }, [classification, subclass]);

  useEffect(() => {
    const fetchActualUses = async () => {
      if (!classification) {
        setActualUses([]);
        setActualUse('');
        setIsLoadingActualUses(false);
        return;
      }

      setIsLoadingActualUses(true);
      try {
        const actualUsedData = await getActualUsedByClassId(classification);
        setActualUses(actualUsedData || []);

        if (actualUse && !actualUsedData?.some(a => a.actual_used_id === actualUse)) {
          setActualUse('');
        }
      } catch (error) {
        console.error('Error fetching actual uses:', error);
        setActualUses([]);
        setActualUse('');
      } finally {
        setIsLoadingActualUses(false);
      }
    };

    fetchActualUses();
  }, [classification, actualUse]);

  useEffect(() => {
    const baseValid = district !== null &&
      declarant.trim() !== '' &&
      kind.trim() !== '' &&
      classification.trim() !== '' &&
      actualUse.trim() !== '';

    const isValid = isMachineryKind ? baseValid : baseValid && area > 0;

    setIsFormValid(isValid);
  }, [district, declarant, kind, classification, area, actualUse, isMachineryKind]);

  const resetForm = useCallback(() => {
    setDistrict(null);
    setDeclarant('');
    setKind('');
    setClassification('');
    setSubclass('');
    setActualUse('');
    setArea(0);
    setBuildingData(null);
    setMachineData(null);
    setAgriculturalData(null);
  }, []);

  const handleNextClick = useCallback(() => {
    if (!isFormValid) return;

    if (isBuilding) {
      setShowBuildingModal(true);
    } else if (isMachineryKind) {
      setShowMachineModal(true);
    } else if (isAgriculturalLand) {
      setShowAgriculturalModal(true);
    } else {
      setShowPhotoModal(true);
    }
  }, [isFormValid, isBuilding, isMachineryKind, isAgriculturalLand]);

  const handleBuildingModalSuccess = useCallback((buildingData: any) => {
    setBuildingData(buildingData);
    setShowBuildingModal(false);
    setShowPhotoModal(true);
  }, []);

  const handleBuildingModalDismiss = useCallback(() => {
    setShowBuildingModal(false);
  }, []);

  const handleMachineModalSuccess = useCallback((machineData: MachineData) => {
    setMachineData(machineData);
    setShowMachineModal(false);
    setShowPhotoModal(true);
  }, []);

  const handleMachineModalClose = useCallback(() => {
    setShowMachineModal(false);
  }, []);

  const handleAgriculturalModalSuccess = useCallback((adjustmentData: AgriculturalLandAdjustmentData) => {
    setAgriculturalData(adjustmentData);
    setShowAgriculturalModal(false);
    setShowPhotoModal(true);
  }, []);

  const handleAgriculturalModalDismiss = useCallback(() => {
    setShowAgriculturalModal(false);
  }, []);

  const handlePhotoModalClose = useCallback(() => {
    setShowPhotoModal(false);
    resetForm();
    onSuccess();
  }, [resetForm, onSuccess]);

  const handlePhotoModalSuccess = useCallback(() => {
    setShowPhotoModal(false);
    resetForm();
    onSuccess();
  }, [resetForm, onSuccess]);

  const handleDismiss = useCallback(() => {
    resetForm();
    onDismiss();
  }, [resetForm, onDismiss]);

  return (
    <>
      <FormView
        isOpen={isOpen}
        onDismiss={handleDismiss}
        district={district}
        setDistrict={setDistrict}
        declarant={declarant}
        setDeclarant={setDeclarant}
        kind={kind}
        setKind={setKind}
        classification={classification}
        setClassification={setClassification}
        subclass={subclass}
        setSubclass={setSubclass}
        actualUse={actualUse}
        setActualUse={setActualUse}
        area={area}
        setArea={setArea}
        onNextClick={handleNextClick}
        isFormValid={isFormValid}
        districts={districts}
        kinds={kinds}
        classifications={classifications}
        subclasses={subclasses}
        actualUses={formattedActualUses}
        isLoadingDistricts={isLoadingDistricts}
        isLoadingKinds={isLoadingKinds}
        isLoadingClassifications={isLoadingClassifications}
        isLoadingSubclasses={isLoadingSubclasses}
        isLoadingActualUses={isLoadingActualUses}
        isBuildingKind={isBuilding}
        isLandKind={isLandKind}
        isMachineryKind={isMachineryKind}
      />

      {showBuildingModal && (
        <BuildingModal
          isOpen={showBuildingModal}
          onDismiss={handleBuildingModalDismiss}
          onSuccess={handleBuildingModalSuccess}
          formData={formData}
        />
      )}

      <MachineModal
        isOpen={showMachineModal}
        onClose={handleMachineModalClose}
        onSuccess={handleMachineModalSuccess}
      />

      <AgriculturalLandAdjustmentModal
        isOpen={showAgriculturalModal}
        onDismiss={handleAgriculturalModalDismiss}
        onSuccess={handleAgriculturalModalSuccess}
        formData={formData}
      />

      <PhotoModal
        isOpen={showPhotoModal}
        onClose={handlePhotoModalClose}
        onPhotoTaken={() => { }}
        formData={formData}
        buildingData={buildingData}
        machineData={machineData}
        agriculturalData={agriculturalData}
        onCompleteSubmission={handlePhotoModalSuccess}
      />
    </>
  );
};

export default React.memo(Form);